### ISSUE TITLE
Rather cryptic error when --token-network-registry-address is missing from deploy services script

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1168]
When I execute
```
python -m raiden_contracts.deploy services --rpc-provider $GOERLI --private-key $GOERLIPRIV --gas-price 20 --gas-limit 6000000 --token-address  0x291e3F53D2Ea6cc4040419dEf5486cfd572f838d --user-deposit-whole-limit $MAX_UINT256 --service-deposit-bump-numerator 6 --service-deposit-bump-denominator 5 --service-deposit-decay-constant $decay --initial-service-deposit-price $Deposit --service-deposit-min-price 1000 --service-registration-duration $duration
```
I get
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 457, in <module>
    main()
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 302, in services
    token_network_registry_address=token_network_registry_address,
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_deployer.py", line 363, in deploy_service_contracts
    deployed_contracts=deployed_contracts,
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_deployer.py", line 196, in _deploy_and_remember
    receipt = self.deploy(contract_name, arguments)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_deployer.py", line 78, in deploy
    txhash = self.send_deployment_transaction(contract=contract, args=args)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_deployer.py", line 107, in send_deployment_transaction
    txhash = contract.constructor(*args).transact(self.transaction)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/contract.py", line 342, in constructor
    **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/contract.py", line 798, in __init__
    self.data_in_transaction = self._encode_data_in_transaction(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/utils/decorators.py", line 14, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/contract.py", line 812, in _encode_data_in_transaction
    encode_abi(self.web3, constructor_abi, arguments, data=self.bytecode)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/utils/contracts.py", line 138, in encode_abi
    ', '.join(argument_types),
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: address, address, address, address
```

Instead it should complain that --token-network-registry-address is missing.

**Comment by pirapira** [comment]
I can still reproduce this issue.
