### ISSUE TITLE
"Transaction with the same hash was already imported." with Parity

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1275]
`deployer` script fails with the following error.  This looks similar to https://github.com/raiden-network/raiden/issues/3263 .

```
DEBUG:raiden_contracts.deploy.contract_deployer:Calling UserDeposit.init() with msc_address=0xBe41B9CE4042B1fdeb0aBC56036Cb29BB0D24181 one_to_n_address=0x4e9444868fb4F1e05b8B06909d876e5fCf9c825E
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 481, in <module>
    main()
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 326, in services
    token_network_registry_address=token_network_registry_address,
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_deployer.py", line 379, in deploy_service_contracts
    _msc_address=msc.address, _one_to_n_address=one_to_n.address
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_deployer.py", line 95, in transact
    txhash = contract_method.transact(self.transaction)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/contract.py", line 1151, in transact
    **self.kwargs
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/contract.py", line 1454, in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/eth.py", line 269, in sendTransaction
    [transaction],
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32010, 'message': 'Transaction with the same hash was already imported.'}
```

**Comment by pirapira** [comment]
The transaction hash depends on the calldata, nonce and so on.  So we just need to calculate the transaction hash and wait for it to be mined.

**Comment by Dominik1999** [comment]
Needs investigation maybe together with @hackaugusto
