### ISSUE TITLE
Problems found while deploying contracts in Goerli

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden-contracts#1340]
I deployed contracts in the Goerli network after following the Readme guide and found some problems which I solved and will follow in a PR. And some which still need investigation.

### Deploying main contracts
```
python -m raiden_contracts.deploy raiden --rpc-provider http://parity.goerli.ethnodes.brainbot.com:8545 --private-key XXX -gas-price 10 --gas-limit 6000000 --max-token-networks 1
```

Worked fine

```
Web3 provider is RPC connection http://parity.goerli.ethnodes.brainbot.com:8545
Enter the private key password: 
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying SecretRegistry txHash=0xe4e163ebc3986902ca0b2bc91507033f756716b11075b94f121105d260189b67, contracts version None
INFO:raiden_contracts.deploy.contract_deployer:SecretRegistry address: 0xE385296a8FCEe7cd460FA7984c034632E899D715. Gas used: 252818
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying TokenNetworkRegistry txHash=0x10cd448a010e233bcc8cce75bdc3523f6b99e33350ee573060d75c3e89bef542, contracts version None
INFO:raiden_contracts.deploy.contract_deployer:TokenNetworkRegistry address: 0x2150Ce8D94bB54DA2927738685c4a56ed50D3be6. Gas used: 4138906
Deployment information for chain id = 5  has been updated at /home/lefteris/ew/raiden-contracts/raiden_contracts/data/deployment_goerli.json.
SecretRegistry at 0xE385296a8FCEe7cd460FA7984c034632E899D715 matches the compiled data from contracts.json
TokenNetworkRegistry at 0x2150Ce8D94bB54DA2927738685c4a56ed50D3be6 matches the compiled data from contracts.json
Deployment info from /home/lefteris/ew/raiden-contracts/raiden_contracts/data/deployment_goerli.json has been verified and it is CORRECT.
{
    "SecretRegistry": "0xE385296a8FCEe7cd460FA7984c034632E899D715",
    "TokenNetworkRegistry": "0x2150Ce8D94bB54DA2927738685c4a56ed50D3be6"
}
```

## Deploying a test token

```
python -m raiden_contracts.deploy token --rpc-provider http://parity.goerli.ethnodes.brainbot.com:8545 --private-key XXX --gas-price 10 --token-supply 20000000 --token-name ServiceToken --token-decimals 18 --token-symbol SVT
```

Worked fine:

```
Web3 provider is RPC connection http://parity.goerli.ethnodes.brainbot.com:8545
Enter the private key password: 
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying CustomToken txHash=0x15b13ad7c890926ec36435cd14e8d54968181781bfe2177417083340374cd751, contracts version None
INFO:raiden_contracts.deploy.contract_deployer:CustomToken address: 0xc280D18ec932Da2BE520597eC5E48BA2eF595068. Gas used: 1213958
{
    "CustomToken": "0xc280D18ec932Da2BE520597eC5E48BA2eF595068"
}
```

### Deploying Services

```
python -m raiden_contracts.deploy services --rpc-provider http://parity.goerli.ethnodes.brainbot.com:8545  --private-key XXX --gas-price 10 --gas-limit 6000000 --token-address 0xc280D18ec932Da2BE520597eC5E48BA2eF595068 --user-deposit-whole-limit 10000000000 --service-deposit-bump-numerator 3 --service-deposit-bump-denominator 2  --service-deposit-decay-constant 1000 --initial-service-deposit-price 1000000000000000 --service-deposit-min-price 100 --service-registration-duration 7200 --token-network-registry-address 0x2150Ce8D94bB54DA2927738685c4a56ed50D3be
```

It did not work at first because many arguments needed were not documented but I added them and will open a PR to add them to the docs. It worked afterwards but there was an exception raised during verification which needs to be investigated. The contracts are deployed properly though.

```
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying ServiceRegistry txHash=0x2c9143cb4268a963d432d5caa27fc0667946202aefdc03502c7c96e7bc5f0478, contracts version None
INFO:raiden_contracts.deploy.contract_deployer:ServiceRegistry address: 0x0c4C6C310D38A5bc049E94f68a34d72F96738fbB. Gas used: 2022049
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying UserDeposit txHash=0x8344a2b4c81b828e2d16e56f6d6cba441ea921b5775cfdfcb54af53739b3c602, contracts version None
INFO:raiden_contracts.deploy.contract_deployer:UserDeposit address: 0xF9EF12aE5AA19fD834c08448efD6BA49bB4CB11b. Gas used: 1553020
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying MonitoringService txHash=0x16ea4bf1bef71f60dae4d831db9e7e67590307dcffbb9cb18f56864f863e5c87, contracts version None
INFO:raiden_contracts.deploy.contract_deployer:MonitoringService address: 0x6Df6911E7b8E8E921579B4b3865afDAF13Df8102. Gas used: 2039589
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying OneToN txHash=0xc91f97965f7d1e796afbdc59946dc61dd2c01c48eaa8ff9606fd8c1564617638, contracts version None
INFO:raiden_contracts.deploy.contract_deployer:OneToN address: 0xA3797ca6Bd39FD427Ea9357eB6Fa47857d322AeB. Gas used: 1137888
DEBUG:raiden_contracts.deploy.contract_deployer:Calling UserDeposit.init() with msc_address=0x6Df6911E7b8E8E921579B4b3865afDAF13Df8102 one_to_n_address=0xA3797ca6Bd39FD427Ea9357eB6Fa47857d322AeB
DEBUG:raiden_contracts.deploy.contract_deployer:Sending txHash=0x6683cc2d24b9bb2f57bfbf3b81caad20d0a537b6e3662a5e9b9f3b571e2eb996
Deployment information for chain id = 5  has been updated at /home/lefteris/ew/raiden-contracts/raiden_contracts/data/deployment_services_goerli.json.
ServiceRegistry at 0x0c4C6C310D38A5bc049E94f68a34d72F96738fbB matches the compiled data from contracts.json
UserDeposit at 0xF9EF12aE5AA19fD834c08448efD6BA49bB4CB11b matches the compiled data from contracts.json
OneToN at 0xA3797ca6Bd39FD427Ea9357eB6Fa47857d322AeB matches the compiled data from contracts.json
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lefteris/ew/raiden-contracts/raiden_contracts/deploy/__main__.py", line 481, in <module>
    main()
  File "/home/lefteris/.virtualenvs/contractspy37/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/contractspy37/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lefteris/.virtualenvs/contractspy37/lib/python3.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/lefteris/.virtualenvs/contractspy37/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lefteris/.virtualenvs/contractspy37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lefteris/ew/raiden-contracts/raiden_contracts/deploy/__main__.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/contractspy37/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lefteris/ew/raiden-contracts/raiden_contracts/deploy/__main__.py", line 338, in services
    token_network_registry_address=token_network_registry_address,
  File "/home/lefteris/ew/raiden-contracts/raiden_contracts/deploy/contract_verifier.py", line 102, in store_and_verify_deployment_info_services
    token_network_registry_address=token_network_registry_address,
  File "/home/lefteris/ew/raiden-contracts/raiden_contracts/deploy/contract_verifier.py", line 78, in verify_deployed_service_contracts_in_filesystem
    token_network_registry_address=token_network_registry_address,
  File "/home/lefteris/ew/raiden-contracts/raiden_contracts/deploy/contract_verifier.py", line 247, in verify_service_contracts_deployment_data
    deployed_contracts_info, CONTRACT_MONITORING_SERVICE
  File "/home/lefteris/ew/raiden-contracts/raiden_contracts/deploy/contract_verifier.py", line 184, in _verify_deployed_contract
    f'We have block_number {contracts[contract_name]["block_number"]} in the '
RuntimeError: We have block_number 1688757 in the deployment info, but 1688758 in the transaction receipt from web3.
```

**Comment by LefterisJP** [comment]
@Dominik1999 as far as the addresses of the deployed contracts are concerned I am adding here the two deployment files:

### Services
```json

{
  "contracts_version": null,
  "chain_id": 5,
  "contracts": {
    "ServiceRegistry": {
      "address": "0x0c4C6C310D38A5bc049E94f68a34d72F96738fbB",
      "transaction_hash": "0x2c9143cb4268a963d432d5caa27fc0667946202aefdc03502c7c96e7bc5f0478",
      "block_number": 1688755,
      "gas_cost": 2022049,
      "constructor_arguments": [
        "0xc280D18ec932Da2BE520597eC5E48BA2eF595068",
        "0x0000000000000000000000000000000000000000",
        1000000000000000,
        3,
        2,
        1000,
        100,
        7200
      ]
    },
    "UserDeposit": {
      "address": "0xF9EF12aE5AA19fD834c08448efD6BA49bB4CB11b",
      "transaction_hash": "0x8344a2b4c81b828e2d16e56f6d6cba441ea921b5775cfdfcb54af53739b3c602",
      "block_number": 1688756,
      "gas_cost": 1553020,
      "constructor_arguments": [
        "0xc280D18ec932Da2BE520597eC5E48BA2eF595068",
        10000000000
      ]
    },
    "MonitoringService": {
      "address": "0x6Df6911E7b8E8E921579B4b3865afDAF13Df8102",
      "transaction_hash": "0x16ea4bf1bef71f60dae4d831db9e7e67590307dcffbb9cb18f56864f863e5c87",
      "block_number": 1688757,
      "gas_cost": 2039589,
      "constructor_arguments": [
        "0xc280D18ec932Da2BE520597eC5E48BA2eF595068",
        "0x0c4C6C310D38A5bc049E94f68a34d72F96738fbB",
        "0xF9EF12aE5AA19fD834c08448efD6BA49bB4CB11b",
        "0x2150Ce8D94bB54DA2927738685c4a56ed50D3be6"
      ]
    },
    "OneToN": {
      "address": "0xA3797ca6Bd39FD427Ea9357eB6Fa47857d322AeB",
      "transaction_hash": "0xc91f97965f7d1e796afbdc59946dc61dd2c01c48eaa8ff9606fd8c1564617638",
      "block_number": 1688759,
      "gas_cost": 1137888,
      "constructor_arguments": [
        "0xF9EF12aE5AA19fD834c08448efD6BA49bB4CB11b",
        5,
        "0x0c4C6C310D38A5bc049E94f68a34d72F96738fbB"
      ]
    }
  }
}
```

### Main contracts

```json
{
  "contracts_version": null,
  "chain_id": 5,
  "contracts": {
    "SecretRegistry": {
      "address": "0xE385296a8FCEe7cd460FA7984c034632E899D715",
      "transaction_hash": "0xe4e163ebc3986902ca0b2bc91507033f756716b11075b94f121105d260189b67",
      "block_number": 1688666,
      "gas_cost": 252818,
      "constructor_arguments": []
    },
    "TokenNetworkRegistry": {
      "address": "0x2150Ce8D94bB54DA2927738685c4a56ed50D3be6",
      "transaction_hash": "0x10cd448a010e233bcc8cce75bdc3523f6b99e33350ee573060d75c3e89bef542",
      "block_number": 1688667,
      "gas_cost": 4138906,
      "constructor_arguments": [
        "0xE385296a8FCEe7cd460FA7984c034632E899D715",
        5,
        500,
        555428,
        1
      ]
    }
  }
}
```
