### ISSUE TITLE
Checking out v2.0.0 of raiden and deploying contracts gives error

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden-contracts#1503]
@palango 
To reproduce the error follow [this](https://raiden-network.readthedocs.io/en/latest/custom-setups/private_net_tutorial.html#install-raiden-and-dependencies) guide here till the deployment of the `SecretRegistry` and `TokenNetworkRegistry` contracts
The genesis.json file is wrongly formatted in the `readThedocs` and will be corrected. meanwhile the `genesis.json` looks like this 
This is a very trivial error. On observing the output we see that the contracts are deployed and it also generates the required deployment files but it fails somewhere at the end.
```
{
"config": {
"chainId": 4321,
"homesteadBlock": 0,
"eip150Block": 0,
"eip155Block": 0,
"eip158Block": 0,
"ByzantiumBlock": 0,
"eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"ConstantinopleBlock": 0,
"PetersburgBlock": 0
},
"alloc": {},
"difficulty" : "0x1",
"gasLimit"   : "0x9880000"
}
```

The actual command output while running the deployment.
```
(env) ubuntu@checkv2Raiden:~/priv_chain$ python -m raiden_contracts.deploy raiden --rpc-provider $PROVIDER --private-key $PRIV_KEY --gas-price 10 --gas-limit 6000000 --contracts-version $VERSION --max-token-networks $MAX_UINT256
Web3 provider is RPC connection http://127.0.0.1:8545
Enter the private key password: 
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying SecretRegistry txHash=0xdb537a1b3bbb3431cfce3ee68f1d0a22774bc635bb2ef2654b818db96ee6cb3a, contracts version 0.37.0
INFO:raiden_contracts.deploy.contract_deployer:SecretRegistry address: 0x06E64DE3a5c723fdde0EA754Af83fD21e46e5c13. Gas used: 292942
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying TokenNetworkRegistry txHash=0x08a8d0742e8a969d020eec03396672beea6cd2daddfc1329a1e2c99aeb7f339c, contracts version 0.37.0
INFO:raiden_contracts.deploy.contract_deployer:TokenNetworkRegistry address: 0xcB3098A28d9842Bae485d943aC2CFdD548Cf56ea. Gas used: 4907650
Deployment information for chain id = 4321  has been updated at /home/ubuntu/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/data_0.37.0/deployment_private_net.json.
SecretRegistry at 0x06E64DE3a5c723fdde0EA754Af83fD21e46e5c13 matches the compiled data from contracts.json
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 564, in <module>
    main()
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 1699, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 241, in raiden
    deployed_contracts_info=deployed_contracts_info
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/contract_verifier.py", line 92, in store_and_verify_deployment_info_raiden
    self.verify_deployed_contracts_in_filesystem()
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/contract_verifier.py", line 52, in verify_deployed_contracts_in_filesystem
    if self.verify_deployment_data(deployment_data):
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/contract_verifier.py", line 135, in verify_deployment_data
    deployment_data=deployment_data, contract_name=CONTRACT_TOKEN_NETWORK_REGISTRY
  File "/home/ubuntu/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/contract_verifier.py", line 212, in _verify_deployed_contract
    library_address=contracts[LIBRARY_TOKEN_NETWORK_UTILS]["address"],
KeyError: 'TokenNetworkUtils'
```

**Comment by palango** [comment]
Yes, this is a bug that was introduced when the library was added.

Will be fixed with https://github.com/raiden-network/raiden-contracts/pull/1501

**Comment by agatsoh** [comment]
@palango i dont encounter this bug on the latest develop branch though, so after your PR are we going to make another release of raiden ?
