### ISSUE TITLE
Installation fails with wrong solidity version installed

### ISSUE THREAD

**Issue by schmir** [raiden-network/raiden-contracts#280]
I'm trying to install raiden-contracts with `pip install raiden-contracts` and get the following error.
```
...
  Running setup.py install for raiden-contracts ... error
    Complete output from command /home/ralf/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cpwuj17j/raiden-contracts/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cgvifanb/install-record.txt --single-version-externally-managed --compile --install-headers /home/ralf/local/include/site/python3.6/raiden-contracts:
    running install
    running build
    running build_py
    running compile_contracts
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cpwuj17j/raiden-contracts/setup.py", line 118, in <module>
        setup(**config)
      File "/home/ralf/local/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ralf/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-cpwuj17j/raiden-contracts/setup.py", line 32, in run
        self.run_command('compile_contracts')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-cpwuj17j/raiden-contracts/setup.py", line 73, in run
        contract_manager.store_compiled_contracts(CONTRACTS_PRECOMPILED_PATH)
      File "/tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contract_manager.py", line 113, in store_compiled_contracts
        self._compile_all_contracts()
      File "/tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contract_manager.py", line 77, in _compile_all_contracts
        optimize=False,
      File "/home/ralf/local/lib/python3.6/site-packages/solc/main.py", line 135, in compile_files
        stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
      File "/home/ralf/local/lib/python3.6/site-packages/solc/utils/string.py", line 85, in inner
        return force_obj_to_text(fn(*args, **kwargs))
      File "/home/ralf/local/lib/python3.6/site-packages/solc/wrapper.py", line 169, in solc_wrapper
        stderr_data=stderrdata,
    solc.exceptions.SolcError: An error occurred during execution
            > command: `solc --combined-json abi,bin,ast raiden=/tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts test=/tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/test /tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/TokenNetwork.sol /tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/EndpointRegistry.sol /tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/SecretRegistry.sol /tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/Utils.sol /tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/TokenNetworkRegistry.sol /tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/Token.sol`
            > return code: `1`
            > stderr:
    
            > stdout:
            /tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/TokenNetwork.sol:211:16: Error: Expected identifier, got 'LParen'
        constructor(
                   ^
    /tmp/pip-install-cpwuj17j/raiden-contracts/raiden_contracts/contracts/TokenNetworkRegistry.sol:33:16: Error: Expected identifier, got 'LParen'
        constructor(
                   ^
    
    ----------------------------------------
Command "/home/ralf/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cpwuj17j/raiden-contracts/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cgvifanb/install-record.txt --single-version-externally-managed --compile --install-headers /home/ralf/local/include/site/python3.6/raiden-contracts" failed with error code 1 in /tmp/pip-install-cpwuj17j/raiden-contracts/
```

I've got solidity version 0.4.21 installed. It looks like the minimum version required for compilation of the contracts is 0.4.23. If I remove solidity or install version 0.4.23 installation works.

The raiden-contracts package includes a gzipped version of the compiled contracts, so there is no need to compile the contracts while installing the package.  

My recommendation would be to never try to compile the contracts unless explicitly asked to do that.
This makes the installation less surprising and more predictable.

**Comment by schmir** [comment]
btw. this bug also happens during a `pip install raiden`.

**Comment by loredanacirstea** [comment]
Yes, the default should be to not compile the contracts unless explicitly asked. We need to fix this.

**Comment by loredanacirstea** [comment]
In my local environment this works correctly, because `pip install raiden-contracts` does not run `python setup.py install`. It runs `make install` - which does not compile the contracts.

So, the issue is with `python setup.py install`, because this also runs `python setup.py build`, which is set to try to compile the contracts: https://github.com/raiden-network/raiden-contracts/blob/089ea635b53cfd84c84f37bce39c49b88aa9dd7e/setup.py#L112, https://github.com/raiden-network/raiden-contracts/blob/089ea635b53cfd84c84f37bce39c49b88aa9dd7e/setup.py#L31-L34

But when there are different `solc` versions, we get this `solc.exceptions.SolcError` that is not handled.

Solutions:
- to just handle this `SolcError` and do the contracts compilation if possible.
- extend the `from setuptools.command.install` to not build the contracts

@pcppcp , what do you think?

**Comment by pcppcp** [comment]
maybe a different pip/setup tools behavior for different versions? Or package type? If I do `pip install raiden-contracts` in my venv, the build step isn't trigerred. We should investigate first why it is executed on @schmir's machine.

**Comment by loredanacirstea** [comment]
> maybe a different pip/setup tools behavior for different versions?

Yes, probably. Still, shouldn't we also support `python setup.py install` even though it is being slowly deprecated in favor of `pip`? Other people might use similar tool versions or just want to install the package this way for various reasons (I see some namespace issues can arise https://github.com/pypa/setuptools/issues/960).

**Comment by pcppcp** [comment]
I can reproduce schmir's problem if I do `pip install raiden-contracts --no-cache-dir` without `solc` in the `$PATH`.
I thought the build is triggered only for `sdist`, but with `setup.py install` it fires as well. There's a check that skips the build part for `dist`, but this doesn't happen for the installation...

**Comment by pcppcp** [comment]
So the option where we remove contracts compilation from build is probably the best shot. Or `solc` can be made a mandatory requirement.

Maybe someone with better insight to pip build/install process could suggest other way out, maybe @ulope?

**Comment by LefterisJP** [comment]
This should be done thanks to #295
