### ISSUE TITLE
Deployment error on 0.3._: `eth_abi.exceptions.InsufficientDataBytes`

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#440]
Reported on Gitter https://gitter.im/raiden-network/raiden?at=5c37a33b783a5553d812fbe5. Needs more info (e.g. result of `pip freeze`, especially for `eth_abi` version).

> had to run both pip install -r requirements_dev.txt and pip install -r requirements.txt, you may want to mention this under that section. Also the - contracts-version 0.3._ should be without the quotes : - contracts-version 0.3._ (with the quotes if will fail).
I managed to run the raiden and token commands with the new flag. The 'register command fails with:

```
DEBUG:main:calling createERC20TokenNetwork(0x67F69093b2C4A3ef23A37EF0A10f6FB8DA972141) txHash=0x77bb802482b0d595aeb1b9b22a1fda9e6ade7c507e42558a0d6abce627f1a846
Traceback (most recent call last):
File "/home/offerm/raiden-contracts/venv/lib/python3.6/site-packages/web3/contract.py", line 1372, in call_contract_function
output_data = decode_abi(output_types, return_data)
File "/home/offerm/raiden-contracts/venv/lib/python3.6/site-packages/eth_abi/abi.py", line 96, in decode_abi
return decoder(stream)
File "/home/offerm/raiden-contracts/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in call
return self.decode(stream)
File "/home/offerm/raiden-contracts/venv/lib/python3.6/site-packages/eth_utils/functional.py", line 46, in inner
return callback(fn(args, *kwargs))
File "/home/offerm/raiden-contracts/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 164, in decode
yield decoder(stream)
File "/home/offerm/raiden-contracts/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in call
return self.decode(stream)
File "/home/offerm/raiden-contracts/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 186, in decode
raw_data = self.read_data_from_stream(stream)
File "/home/offerm/raiden-contracts/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 296, in read_data_from_stream
len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes. Only got 0 bytes
```

**Comment by palango** [comment]
Closing, as this is old and the code changed quite bit.
