### ISSUE TITLE
Failed to deploy contracts on private network

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden-contracts#490]
Trying to deploy I have the following error
```
(raiden-contracts) admins-MacBook-Pro-2:raiden-contracts admin$ python -m raiden_contracts.deploy raiden --rpc-provider http://127.0.0.1:8545 --private-key $private_key --gas-price 10 --gas-limit 6000000 --contracts-version 0.4.0
Web3 provider is RPC connection http://127.0.0.1:8545
Enter the private key password: 
INFO:__main__:Skipped checks against the source code because it is not available.
DEBUG:__main__:Deploying EndpointRegistry txHash=0xf35cba813872823d3735528b85161a1cc608ccf7ae15d7f800c04401c7bc00da, contracts version 0.4.0
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/admin/xud-eth/raiden-contracts/raiden_contracts/deploy/__main__.py", line 831, in <module>
    main()
  File "/Users/admin/.virtualenvs/raiden-contracts/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden-contracts/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/admin/.virtualenvs/raiden-contracts/lib/python3.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/admin/.virtualenvs/raiden-contracts/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/.virtualenvs/raiden-contracts/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/xud-eth/raiden-contracts/raiden_contracts/deploy/__main__.py", line 177, in wrapper
    return func(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden-contracts/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/xud-eth/raiden-contracts/raiden_contracts/deploy/__main__.py", line 247, in raiden
    deployed_contracts_info = deploy_raiden_contracts(deployer)
  File "/Users/admin/xud-eth/raiden-contracts/raiden_contracts/deploy/__main__.py", line 447, in deploy_raiden_contracts
    endpoint_registry_receipt = deployer.deploy(CONTRACT_ENDPOINT_REGISTRY)
  File "/Users/admin/xud-eth/raiden-contracts/raiden_contracts/deploy/__main__.py", line 115, in deploy
    (receipt, tx) = check_succesful_tx(self.web3, txhash, self.wait)
  File "/Users/admin/xud-eth/raiden-contracts/raiden_contracts/utils/transaction.py", line 15, in check_succesful_tx
    if receipt['status'] == 0:
  File "/Users/admin/.virtualenvs/raiden-contracts/lib/python3.7/site-packages/web3/datastructures.py", line 32, in __getitem__
    return self.__dict__[key]
KeyError: 'status'
(raiden-contracts) admins-MacBook-Pro-2:raiden-contracts admin$ 
```

I'm using the `master` branch of raiden-contacts and geth version `1.8.0-stable`
Running on `macos`

**Comment by offerm** [comment]
I think this is the genesis file I used 
```
"config": {
"chainId": 4321,
"homesteadBlock": 0,
"eip155Block": 0,
"eip158Block": 0
},
"alloc": {},
"difficulty" : "0x20000",
"gasLimit"   : "0x8880000"
}
```

You may be able to confirm with this:
```
> eth.getBlock(0)
{
  difficulty: 131072,
  extraData: "0x",
  gasLimit: 143130624,
  gasUsed: 0,
  hash: "0xfbb8b4d7030ca64b914594525f43e1a464e6a631d6fea217ab64051ec62baa59",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 508,
  stateRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  timestamp: 0,
  totalDifficulty: 131072,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
> 
```
geth command:

>geth --rpc --datadir blkchain1 --bootnodes enode://b16590aa32d2f0ad2e0bb0b1d141886a225171e27ec468336e7965a4217afafc85c3141fd8e56e97c5a471bf4d84244af9d3c868a9c15c36d85822af88030489@127.0.0.1:30303  --networkid 4321 console


@pirapira let me know if you need anything else.

**Comment by pirapira** [comment]
I think I can try this today.

**Comment by hackaugusto** [comment]
`status` is part of [byzantium](https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement/), perhaps it's missing the entry `'ByzantiumBlock': 0,` to enable this feature in the receipts.

For a reference genesis config, you can check the [genesis.py](https://github.com/raiden-network/raiden/blob/d50045c7aec544d225dcddc4fb2ee81f35e1949e/raiden/tests/utils/genesis.py) in the raiden repo (note it's python code and not valid json)

**Comment by pirapira** [comment]
@offerm will you try what @hackaugusto said ^?

I created an issue about adding a more helpful error message in this case https://github.com/raiden-network/raiden-contracts/issues/498.

**Comment by offerm** [comment]
Yes. Will try and let you know

**Comment by pirapira** [comment]
@offerm your feedbacks are really helpful.  Thank you very much.

**Comment by offerm** [comment]
@pirapira @hackaugusto Many thanks for your help. This one can be closed. `'ByzantiumBlock': 0,` is needed. Please consider to update the setup instructions.
