### ISSUE TITLE
mypy_extensions missing from requirements.txt

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#778]
```
python -m raiden_contracts.deploy raiden --rpc-provider http://127.0.0.1:8545  --private-key /home/yoichi/xud-eth/blkchain1/keystore/UTC--2019-03-26T15-46-54.573149705Z--b772b74bc6021aab88ef154d76eb3174258e3865 --gas-price 10 --gas-limit 6000000  --contracts-version 0.3._
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 14, in <module>
    from mypy_extensions import TypedDict
ModuleNotFoundError: No module named 'mypy_extensions'
```

So `mypy_extensions` needs to be in `requirements.txt`.

**Comment by LefterisJP** [comment]
@pirapira We are not using TypedDict in raiden. This seems to be used only in contracts.

**Comment by pirapira** [comment]
Yeah, this is a `raiden-contracts` issue.  So it should be in that repo... oh it's here.

**Comment by LefterisJP** [comment]
@pirapira I can move the issue for you if you want. Or we can just simply leave it and close it when you fix it in the contracts.

**Comment by pirapira** [comment]
To me this page is in contracts
`https://github.com/raiden-network/raiden-contracts/issues/778` .

**Comment by LefterisJP** [comment]
Hm the heck? For me too now. I can swear it was in Raiden before ^_^. Anyway!
