### ISSUE TITLE
Deployment assertion failure with a wrong blocknumber

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#795]
On `geth` running a private chain, I see

```
python -m raiden_contracts.deploy raiden --rpc-provider http://127.0.0.1:8545  --private-key /home/yoichi/xud-eth/blkchain1/keystore/UTC--2019-03-26T15-46-54.573149705Z--b772b74bc6021aab88ef15
4d76eb3174258e3865 --gas-price 10 --gas-limit 6000000  --contracts-version 0.10.1 --max-token-networks 115792089237316195423570985008687907853269984665640564039457584007913129639935
Web3 provider is RPC connection http://127.0.0.1:8545                                                                                                   
Enter the private key password:                                        
DEBUG:__main__:Deploying EndpointRegistry txHash=0xfb12d96c4c9753f28a965cd8a8801d2849d9954effc5d664dcab8a9d7e9a2200, contracts version 0.10.1
INFO:__main__:EndpointRegistry address: 0x611301dE7708492BE56344a9Bf18138eCB477e89. Gas used: 555366
DEBUG:__main__:Deploying SecretRegistry txHash=0x451242d22ee1cd2c270a589d044ebb60b1fd2ecd1c2328000102599b691e7497, contracts version 0.10.1
INFO:__main__:SecretRegistry address: 0xefAD231Ff6278250b63f4424516b6C75E4a5f9e9. Gas used: 313338
DEBUG:__main__:Deploying TokenNetworkRegistry txHash=0x7142319c2899b96a5570f9140aae0d26363b835eedc5d8c6be168631a9206127, contracts version 0.10.1
INFO:__main__:TokenNetworkRegistry address: 0x5432d02758F42A2fA2f04589EC14EB064a4134F9. Gas used: 4755856
Deployment information for chain id = 4321  has been updated at /home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/data_0.10.1/deployment_private_net.json.
EndpointRegistry at 0x611301dE7708492BE56344a9Bf18138eCB477e89 matches the compiled data from contracts.json
Traceback (most recent call last):                                                                                                                                                              
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main                                                                                                               
    "__main__", mod_spec)           
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code           
    exec(code, run_globals)                                                                                                                                                                       File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 1098, in <module>
    main()                 
  File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/click/core.py", line 722, in __call__                     
    return self.main(*args, **kwargs)                                                                                                                                                             File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/click/core.py", line 697, in main       
    rv = self.invoke(ctx)                                                  
  File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/click/core.py", line 1092, in invoke  
    rv.append(sub_ctx.command.invoke(sub_ctx))                                             
  File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)                                                                                                                                                              File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 206, in wrapper
    return func(*args, **kwargs)                                      
  File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)                                                                                                                                           
  File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 408, in raiden                                                          
    save_info=save_info,                                                                                                                                                                          File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 275, in store_and_verify_deployment_info_raiden
    deployer.contract_manager,                                                                                        
  File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 907, in verify_deployed_contracts_in_filesystem
    if verify_deployment_data(web3, contract_manager, deployment_data):                            
  File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 860, in verify_deployment_data
    contract_name=CONTRACT_ENDPOINT_REGISTRY,                                                                                                                                                     File "/home/yoichi/.virtualenvs/offerm-script/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 1060, in verify_deployed_contract
    f'We have block_number {contracts[contract_name]["block_number"]} '
AssertionError: We have block_number 5038 instead of 4536
```

**Comment by pirapira** [comment]
In the AssertionError, the wording `We have` is not informative.  The message should say something else.  https://github.com/raiden-network/raiden-contracts/issues/796

**Comment by pirapira** [comment]
This issue happened when I followed https://github.com/raiden-network/raiden-contracts/issues/795

**Comment by pirapira** [comment]
But I cannot reproduce this anymore.
