### ISSUE TITLE
KeyError: 'status' while deploying raiden contracts on private testnet

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden-contracts#797]
Using this blog I make two nodes
https://medium.freecodecamp.org/how-to-set-up-a-multi-node-private-ethereum-blockchain-from-scratch-in-20-mins-or-less-e0d7e091e062

The way I start both nodes
Node1
---------------------------------------------------------------------------
geth --datadir ~/privateblockchain/ init genesis.json
geth --datadir ~/privateblockchain/ --nodiscover --networkid 1234 --rpc --rpccorsdomain "*"
geth attach ~/privateblockchain/geth.ipc

===========================================
Node2
---------------------------------------------------------------------------
geth --datadir ~/privateblockchain2/ init genesis.json
geth --datadir ~/privateblockchain2/ --nodiscover --networkid 1234 --port 30304 --rpc --rpcport 8546 --rpccorsdomain "*"
geth attach ~/privateblockchain2/geth.ipc

------------------------------------------------------------------------------------------
sync either nodes put the enode of one node as peer of the other node by the 
admin.addPeer("enode://a2e39.......")

Due to solidity errors that I encountered in earlier i installed 0.4.25 using Kelsos's script instead of the latest 0.5
https://github.com/agatsoh/test-environment-scripts#before-installing

Then afterwards i go ahead to deploy the raiden contracts(0.17.0) this way

```
python -m raiden_contracts.deploy raiden --rpc-provider http://127.0.0.1:8545 --private-key ~/privateblockchain/keystore/UTC--2019-03-25T14-48-31.586431707Z--153c58ce3bde3145989e0809c585df35cabc755f --gas-price 10 --gas-limit 6000000 --max-token-networks 1
```

While running the above command I encounter this error 

```
(test-scripts) [krishna@krishna-pc test-environment-scripts]$ python -m raiden_contracts.deploy raiden --rpc-provider http://127.0.0.1:8545 --private-key ~/privateblockchain/keystore/UTC--2019-03-25T14-48-31.586431707Z--153c58ce3bde3145989e0809c585df35cabc755f --gas-price 10 --gas-limit 6000000 --max-token-networks 1
Web3 provider is RPC connection http://127.0.0.1:8545
Enter the private key password: 
DEBUG:raiden_contracts.deploy.contract_deployer:Deploying EndpointRegistry txHash=0xa4dff1a34484a37a57d211444b305f20f224f3694c231a256db08f44e2a82e18, contracts version None
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 699, in <module>
    main()
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 232, in raiden
    max_num_of_token_networks=max_token_networks,
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 523, in deploy_raiden_contracts
    deploy_and_remember(CONTRACT_ENDPOINT_REGISTRY, [], deployer, deployed_contracts)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 494, in deploy_and_remember
    receipt = deployer.deploy(contract_name, arguments)
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/raiden_contracts/deploy/contract_deployer.py", line 81, in deploy
    timeout=self.wait,
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/raiden_contracts/utils/transaction.py", line 13, in check_successful_tx
    if receipt['status'] == 0:
  File "/home/krishna/Envs/test-scripts/lib/python3.7/site-packages/web3/datastructures.py", line 32, in __getitem__
    return self.__dict__[key]
KeyError: 'status'
```

```
(test-scripts) [krishna@krishna-pc test-environment-scripts]$ pip freeze|grep raiden-contracts
raiden-contracts==0.17.0
(test-scripts) [krishna@krishna-pc test-environment-scripts]$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++
   
```

**Comment by pirapira** [comment]
I'll try to reproduce this.

**Comment by pirapira** [comment]
Yes, I see the issue.  Node 2 is not necessary.

**Comment by pirapira** [comment]
This is because the private network is not yet on Byzantium.

Add
```
"homesteadBlock": 0,
"eip150Block": 0,
"eip155Block": 0,
"eip158Block": 0,
"ByzantiumBlock": 0
```
in the genesis config.

@agatsoh will you try setting fork blocks like above?

**Comment by agatsoh** [comment]
Ok I will try doing this

**Comment by agatsoh** [comment]
Hello @pirapira I was successfully able to deploy raiden contracts in one geth with adding `"ByzantiumBlock": 0` to the config object inside genesis.json. How do we do it in a multinode system in private network. On the second node I added the same `"ByzantiumBlock": 0` inside genesis.json, initialised the geth, started geth, added the earlier node as peer but it started rejecting the blocks.
```

INFO [04-04|14:58:32.268] Block synchronisation started 
WARN [04-04|14:58:32.730] Header broke chain ancestry              peer=99f2adc5a39ce81b number=6149 hash=8fd7dc…1e6083
INFO [04-04|14:58:32.778] Imported new chain segment               blocks=21 txs=2 mgas=1.111 elapsed=86.420ms mgasps=12.853 number=5904 hash=06ab7a…de0eb8 age=7m23s   cache=12.35kB
INFO [04-04|14:58:33.092] Imported new chain segment               blocks=171 txs=2 mgas=5.548 elapsed=310.327ms mgasps=17.877 number=6075 hash=1c0c9f…6c2115 age=2m8s    cache=87.39kB
WARN [04-04|14:58:33.130] Synchronisation failed, dropping peer    peer=99f2adc5a39ce81b err="retrieved hash chain is invalid"
WARN [04-04|14:59:04.239] Header broke chain ancestry              peer=99f2adc5a39ce81b number=6158 hash=505ba3…3d97c7
WARN [04-04|14:59:04.525] Synchronisation failed, dropping peer    peer=99f2adc5a39ce81b err="retrieved hash chain is invalid"

```

May be this is out of scope of this issue so if you want you can skip this and may be discuss later.

**Comment by pirapira** [comment]
@agatsoh I never tried a multinode system.  Sorry.
