### ISSUE TITLE
ABI error when trying to deploy a Token contract to a private network

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#852]
When I was preparing a private net deployment guide https://github.com/raiden-network/raiden/pull/3793 I triggared an error with some not-so-helpful error messages.

```
python -m raiden_contracts.deploy token --rpc-provider http://127.0.0.1:8545 --private-key ./blkchain1/keystore/UTC--2019-04-12T12-36-50.139797269Z--1b8e7cbe4937bf95ff6b651e3412a803368ffaaa --gas-price 10 --gas-limit 6000000 --token-supply 115792089237316195423570985008687907853269984665640564039457584007913129639935 --token-name ServiceToken --token-decimals 18 --token-symbol SVT --contracts-version 0.10.1

Web3 provider is RPC connection http://127.0.0.1:8545
Enter the private key password: 
INFO:raiden_contracts.deploy.contract_deployer:Skipped checks against the source code because it is not available.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 679, in <module>
    main()
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/__main__.py", line 364, in token
    token_type=ctx.obj['token_type'],
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/contract_deployer.py", line 139, in deploy_token_contract
    args=[token_supply, token_decimals, token_name, token_symbol],
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/contract_deployer.py", line 70, in deploy
    args=args,
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/raiden_contracts/deploy/contract_deployer.py", line 113, in send_deployment_transaction
    txhash = contract.constructor(*args).transact(
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/web3/contract.py", line 342, in constructor
    **kwargs)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/web3/contract.py", line 798, in __init__
    self.data_in_transaction = self._encode_data_in_transaction(*args, **kwargs)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/web3/utils/decorators.py", line 14, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/web3/contract.py", line 812, in _encode_data_in_transaction
    encode_abi(self.web3, constructor_abi, arguments, data=self.bytecode)
  File "/home/yoichi/priv_chain/env/lib/python3.7/site-packages/web3/utils/contracts.py", line 138, in encode_abi
    ', '.join(argument_types),
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: uint256, uint8, string, string
```

**Comment by pirapira** [comment]
I see the token supply somehow rounded.

```
[115792089237316195423570985008687907853269984665640564039457584007913129639935000000000000000000, 18, 'ServiceToken', 'SVT']
```

**Comment by pirapira** [comment]
In this case, the error should say that the token supply * 10 ^ token_decimals  is too big.
