### ISSUE TITLE
An assertion failure when deploying to Goerli

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#926]
```
(venv) skk% export GOERLI=http://geth.goerli.ethnodes.brainbot.com:8545
export GOERLIPRIV=/home/yoichi/.ethereum/goerli/keystore/UTC--2019-02-18T14-56-34.781524237Z--6c5c227036a1d159c19f17316e5d0f0a52d84d5c
export MAX_UINT256=115792089237316195423570985008687907853269984665640564039457584007913129639935

python -m raiden_contracts.deploy raiden --rpc-provider $GOERLI --private-key $GOERLIPRIV --gas-price 20 --gas-limit 6000000 --max-token-networks
$MAX_UINT256
<snip>
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 443, in <module>
    main()
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.6/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/__main__.py", line 205, in raiden
    deployed_contracts_info=deployed_contracts_info,
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_verifier.py", line 97, in store_and_verify_deployment_info_raiden
    self.verify_deployed_contracts_in_filesystem()
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_verifier.py", line 53, in verify_deployed_contracts_in_filesystem
    if self.verify_deployment_data(deployment_data):
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_verifier.py", line 146, in verify_deployment_data
    contract_name=CONTRACT_ENDPOINT_REGISTRY,
  File "/home/yoichi/src/raiden-contracts/raiden_contracts/deploy/contract_verifier.py", line 210, in _verify_deployed_contract
    f'We have block_number {contracts[contract_name]["block_number"]} in the deployment '
AssertionError: We have block_number 542355 in the deployment info, but 542356 in the transaction receipt from web3.
```

**Comment by pirapira** [comment]
This happens only occasionally.

**Comment by pirapira** [comment]
Not an issue anymore.
